/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuloModuleIdRouteImport } from './routes/modulo.$moduleId'
import { Route as AulaModuleIdLessonIdRouteImport } from './routes/aula.$moduleId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloModuleIdRoute = ModuloModuleIdRouteImport.update({
  id: '/modulo/$moduleId',
  path: '/modulo/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaModuleIdLessonIdRoute = AulaModuleIdLessonIdRouteImport.update({
  id: '/aula/$moduleId/$lessonId',
  path: '/aula/$moduleId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modulo/$moduleId' | '/aula/$moduleId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modulo/$moduleId' | '/aula/$moduleId/$lessonId'
  id: '__root__' | '/' | '/modulo/$moduleId' | '/aula/$moduleId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModuloModuleIdRoute: typeof ModuloModuleIdRoute
  AulaModuleIdLessonIdRoute: typeof AulaModuleIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$moduleId': {
      id: '/modulo/$moduleId'
      path: '/modulo/$moduleId'
      fullPath: '/modulo/$moduleId'
      preLoaderRoute: typeof ModuloModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/$moduleId/$lessonId': {
      id: '/aula/$moduleId/$lessonId'
      path: '/aula/$moduleId/$lessonId'
      fullPath: '/aula/$moduleId/$lessonId'
      preLoaderRoute: typeof AulaModuleIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModuloModuleIdRoute: ModuloModuleIdRoute,
  AulaModuleIdLessonIdRoute: AulaModuleIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
