/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuloModuleIdRouteImport } from './routes/modulo.$moduleId'
import { Route as AulaModuleIdLessonIdRouteImport } from './routes/aula.$moduleId.$lessonId'

const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloModuleIdRoute = ModuloModuleIdRouteImport.update({
  id: '/modulo/$moduleId',
  path: '/modulo/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaModuleIdLessonIdRoute = AulaModuleIdLessonIdRouteImport.update({
  id: '/aula/$moduleId/$lessonId',
  path: '/aula/$moduleId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/comunidade': typeof ComunidadeRoute
  '/conquistas': typeof ConquistasRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/comunidade': typeof ComunidadeRoute
  '/conquistas': typeof ConquistasRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/comunidade': typeof ComunidadeRoute
  '/conquistas': typeof ConquistasRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/comunidade'
    | '/conquistas'
    | '/modulo/$moduleId'
    | '/aula/$moduleId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/comunidade'
    | '/conquistas'
    | '/modulo/$moduleId'
    | '/aula/$moduleId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/comunidade'
    | '/conquistas'
    | '/modulo/$moduleId'
    | '/aula/$moduleId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ComunidadeRoute: typeof ComunidadeRoute
  ConquistasRoute: typeof ConquistasRoute
  ModuloModuleIdRoute: typeof ModuloModuleIdRoute
  AulaModuleIdLessonIdRoute: typeof AulaModuleIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$moduleId': {
      id: '/modulo/$moduleId'
      path: '/modulo/$moduleId'
      fullPath: '/modulo/$moduleId'
      preLoaderRoute: typeof ModuloModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/$moduleId/$lessonId': {
      id: '/aula/$moduleId/$lessonId'
      path: '/aula/$moduleId/$lessonId'
      fullPath: '/aula/$moduleId/$lessonId'
      preLoaderRoute: typeof AulaModuleIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  ComunidadeRoute: ComunidadeRoute,
  ConquistasRoute: ConquistasRoute,
  ModuloModuleIdRoute: ModuloModuleIdRoute,
  AulaModuleIdLessonIdRoute: AulaModuleIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
