/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrilhasRouteImport } from './routes/trilhas'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProvaRouteImport } from './routes/prova'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as LancamentoRouteImport } from './routes/lancamento'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as CertificadoRouteImport } from './routes/certificado'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizModuleIdRouteImport } from './routes/quiz.$moduleId'
import { Route as ModuloModuleIdRouteImport } from './routes/modulo.$moduleId'
import { Route as AulaModuleIdLessonIdRouteImport } from './routes/aula.$moduleId.$lessonId'

const TrilhasRoute = TrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvaRoute = ProvaRouteImport.update({
  id: '/prova',
  path: '/prova',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentoRoute = LancamentoRouteImport.update({
  id: '/lancamento',
  path: '/lancamento',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoRoute = CertificadoRouteImport.update({
  id: '/certificado',
  path: '/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizModuleIdRoute = QuizModuleIdRouteImport.update({
  id: '/quiz/$moduleId',
  path: '/quiz/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloModuleIdRoute = ModuloModuleIdRouteImport.update({
  id: '/modulo/$moduleId',
  path: '/modulo/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaModuleIdLessonIdRoute = AulaModuleIdLessonIdRouteImport.update({
  id: '/aula/$moduleId/$lessonId',
  path: '/aula/$moduleId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/certificado': typeof CertificadoRoute
  '/comunidade': typeof ComunidadeRoute
  '/conquistas': typeof ConquistasRoute
  '/exercicios': typeof ExerciciosRoute
  '/favoritos': typeof FavoritosRoute
  '/lancamento': typeof LancamentoRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRoute
  '/prompts': typeof PromptsRoute
  '/prova': typeof ProvaRoute
  '/ranking': typeof RankingRoute
  '/trilhas': typeof TrilhasRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/quiz/$moduleId': typeof QuizModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/certificado': typeof CertificadoRoute
  '/comunidade': typeof ComunidadeRoute
  '/conquistas': typeof ConquistasRoute
  '/exercicios': typeof ExerciciosRoute
  '/favoritos': typeof FavoritosRoute
  '/lancamento': typeof LancamentoRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRoute
  '/prompts': typeof PromptsRoute
  '/prova': typeof ProvaRoute
  '/ranking': typeof RankingRoute
  '/trilhas': typeof TrilhasRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/quiz/$moduleId': typeof QuizModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/certificado': typeof CertificadoRoute
  '/comunidade': typeof ComunidadeRoute
  '/conquistas': typeof ConquistasRoute
  '/exercicios': typeof ExerciciosRoute
  '/favoritos': typeof FavoritosRoute
  '/lancamento': typeof LancamentoRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/projetos': typeof ProjetosRoute
  '/prompts': typeof PromptsRoute
  '/prova': typeof ProvaRoute
  '/ranking': typeof RankingRoute
  '/trilhas': typeof TrilhasRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
  '/quiz/$moduleId': typeof QuizModuleIdRoute
  '/aula/$moduleId/$lessonId': typeof AulaModuleIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/certificado'
    | '/comunidade'
    | '/conquistas'
    | '/exercicios'
    | '/favoritos'
    | '/lancamento'
    | '/notas'
    | '/onboarding'
    | '/perfil'
    | '/projetos'
    | '/prompts'
    | '/prova'
    | '/ranking'
    | '/trilhas'
    | '/modulo/$moduleId'
    | '/quiz/$moduleId'
    | '/aula/$moduleId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/certificado'
    | '/comunidade'
    | '/conquistas'
    | '/exercicios'
    | '/favoritos'
    | '/lancamento'
    | '/notas'
    | '/onboarding'
    | '/perfil'
    | '/projetos'
    | '/prompts'
    | '/prova'
    | '/ranking'
    | '/trilhas'
    | '/modulo/$moduleId'
    | '/quiz/$moduleId'
    | '/aula/$moduleId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/certificado'
    | '/comunidade'
    | '/conquistas'
    | '/exercicios'
    | '/favoritos'
    | '/lancamento'
    | '/notas'
    | '/onboarding'
    | '/perfil'
    | '/projetos'
    | '/prompts'
    | '/prova'
    | '/ranking'
    | '/trilhas'
    | '/modulo/$moduleId'
    | '/quiz/$moduleId'
    | '/aula/$moduleId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CertificadoRoute: typeof CertificadoRoute
  ComunidadeRoute: typeof ComunidadeRoute
  ConquistasRoute: typeof ConquistasRoute
  ExerciciosRoute: typeof ExerciciosRoute
  FavoritosRoute: typeof FavoritosRoute
  LancamentoRoute: typeof LancamentoRoute
  NotasRoute: typeof NotasRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  ProjetosRoute: typeof ProjetosRoute
  PromptsRoute: typeof PromptsRoute
  ProvaRoute: typeof ProvaRoute
  RankingRoute: typeof RankingRoute
  TrilhasRoute: typeof TrilhasRoute
  ModuloModuleIdRoute: typeof ModuloModuleIdRoute
  QuizModuleIdRoute: typeof QuizModuleIdRoute
  AulaModuleIdLessonIdRoute: typeof AulaModuleIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trilhas': {
      id: '/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof TrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prova': {
      id: '/prova'
      path: '/prova'
      fullPath: '/prova'
      preLoaderRoute: typeof ProvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamento': {
      id: '/lancamento'
      path: '/lancamento'
      fullPath: '/lancamento'
      preLoaderRoute: typeof LancamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado': {
      id: '/certificado'
      path: '/certificado'
      fullPath: '/certificado'
      preLoaderRoute: typeof CertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$moduleId': {
      id: '/quiz/$moduleId'
      path: '/quiz/$moduleId'
      fullPath: '/quiz/$moduleId'
      preLoaderRoute: typeof QuizModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo/$moduleId': {
      id: '/modulo/$moduleId'
      path: '/modulo/$moduleId'
      fullPath: '/modulo/$moduleId'
      preLoaderRoute: typeof ModuloModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/$moduleId/$lessonId': {
      id: '/aula/$moduleId/$lessonId'
      path: '/aula/$moduleId/$lessonId'
      fullPath: '/aula/$moduleId/$lessonId'
      preLoaderRoute: typeof AulaModuleIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CertificadoRoute: CertificadoRoute,
  ComunidadeRoute: ComunidadeRoute,
  ConquistasRoute: ConquistasRoute,
  ExerciciosRoute: ExerciciosRoute,
  FavoritosRoute: FavoritosRoute,
  LancamentoRoute: LancamentoRoute,
  NotasRoute: NotasRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  ProjetosRoute: ProjetosRoute,
  PromptsRoute: PromptsRoute,
  ProvaRoute: ProvaRoute,
  RankingRoute: RankingRoute,
  TrilhasRoute: TrilhasRoute,
  ModuloModuleIdRoute: ModuloModuleIdRoute,
  QuizModuleIdRoute: QuizModuleIdRoute,
  AulaModuleIdLessonIdRoute: AulaModuleIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
